In [2]:
import pandas as pd

In [70]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
pd.set_option('display.max_colwidth', 50)

## Read file

In [98]:
listing_file = pd.read_csv('listings.csv', encoding='iso-8859-1', low_memory=False)

## Delete useless columns

In [131]:
cols = [c for c in listing_file.columns if c.lower()[-3:] != 'url']
listing = listing_file[cols].drop(
    columns=[
        'name', 'host_name', 'scrape_id', 'market', 'host_location', 'smart_location', 'country_code', 'country', 'city', 'state'
    ]
)

listing.shape

(24194, 80)

## Replace bed type with numbers

In [132]:
bed_type_gp = listing.groupby(['bed_type'])
bed_type_gp_list = bed_type_gp.size().reset_index(name='counts')
bed_type_col = bed_type_gp_list.sort_values(['counts'], ascending=False)

In [133]:
replace_num = [i + 1 for i in range(5)]
bed_type_col['Num Represent'] = replace_num
bed_type_col

        bed_type  counts  Num Represent
4       Real Bed   24051              1
2          Futon      69              2
3  Pull-out Sofa      54              3
0         Airbed      11              4
1          Couch       9              5

In [134]:
listing['bed_type'] = list['bed_type'].str.replace('Real Bed', '1').replace('Futon', '2').replace('Pull-out Sofa', '3').replace('Airbed', '4').replace('Couch', '5')

## Delete the symbol "$"

In [135]:
for c in listing:
    try: 
        listing[c].str.replace('$', '')
    except AttributeError:
        pass

In [136]:
listing

,id,last_scraped,experiences_offered,notes,transit,host_id,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,zipcode,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,9835,2019/09/15,none,NaN,"YES ! The bus (305,309) is exactly two blocks ...",33057,2009/08/21,0,0,0.0,f,NaN,1.0,1.0,"['email', 'phone', 'reviews']",f,f,"Bulleen, VIC, Australia",Balwyn North,Manningham,NaN,3105,-37.77268000000000114369,145.09212999999999738066,f,House,Private room,2,1.0,1.0,2.0,1,"{Internet,Wifi,""Pets live on this property"",Do...",NaN,$60.00,NaN,NaN,NaN,NaN,1,$22.00,1,365,1,1,365,365,1.0,365.0,26 months ago,t,30,60,90,365,2019/09/15,4,0,2011/05/24,2015/09/12,90.0,9.0,10.0,10.0,10.0,9.0,9.0,f,NaN,NaN,f,f,strict_14_with_grace_period,f,f,1,0,1,0,0.04000000000000000083
1,10803,2019/09/15,none,NaN,Easy transport options - the tram is right out...,38901,2009/09/16,within an hour,100%,0.0,t,Brunswick,1.0,1.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,"Brunswick East, VIC, Australia",Brunswick,Moreland,NaN,3057,-37.76650999999999669399,144.98073999999999728061,t,Apartment,Private room,2,1.0,1.0,1.0,2,"{TV,Internet,Wifi,""Air conditioning"",Kitchen,H...",226.0,$35.00,$200.00,$803.00,$0.00,$11.00,1,$15.00,3,30,3,3,30,30,3.0,30.0,2 months ago,t,12,19,28,204,2019/09/15,129,30,2013/01/12,2019/08/05,89.0,10.0,9.0,10.0,9.0,9.0,9.0,f,NaN,NaN,t,f,strict_14_with_grace_period,t,t,1,0,1,0,1.59000000000000007994
2,12936,2019/09/14,none,1 set of keys. No luggage storage before/after...,Our apartment is located within walking distan...,50121,2009/10/31,within an hour,100%,0.0,f,St Kilda,13.0,13.0,"['email', 'phone', 'google', 'reviews', 'jumio...",t,t,"St Kilda, VIC, Australia",St Kilda,Port Phillip,NaN,3182,-37.85975999999999430656,144.97737000000000762157,t,Apartment,Entire home/apt,2,1.0,1.0,1.0,1,"{TV,Internet,Wifi,""Air conditioning"",Kitchen,""...",0.0,$159.00,"$1,253.00","$4,452.00",$450.00,$100.00,2,$0.00,3,27,3,3,27,27,3.0,27.0,4 days ago,t,15,23,48,49,2019/09/14,30,17,2010/08/04,2019/07/17,92.0,9.0,9.0,10.0,10.0,9.0,9.0,f,NaN,NaN,f,f,strict_14_with_grace_period,f,f,14,14,0,0,0.27000000000000001776
3,15246,2019/09/14,none,A simple self service breakfast is available ?...,Public transport is super convenient with a ch...,59786,2009/12/03,0,0,0.0,f,Thornbury,3.0,3.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Thornbury, VIC, Australia",Thornbury,Darebin,NaN,3071,-37.75896999999999792408,144.98922999999999206011,t,House,Private room,1,1.5,1.0,1.0,1,"{TV,Internet,Wifi,Kitchen,""Free parking on pre...",0.0,$49.00,$250.00,$920.00,$200.00,$15.00,1,$20.00,2,200,2,2,200,200,2.0,200.0,20 months ago,t,0,0,0,0,2019/09/14,29,0,2010/12/31,2017/05/15,94.0,9.0,9.0,10.0,10.0,9.0,9.0,f,NaN,NaN,f,f,moderate,f,f,2,1,1,0,0.27000000000000001776
4,16760,2019/09/14,none,NaN,NaN,65090,2009/12/22,within a few hours,100%,0.0,f,St Kilda East,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"St Kilda East, VIC, Australia",St Kilda East,Port Phillip,NaN,3183,-37.86453000000000201908,144.99223999999998113708,t,House,Private room,2,1.0,1.0,1.0,1,"{Internet,Wifi,Heating,Washer,""Smoke detector""...",NaN,$68.00,$400.00,"$1,900.00",NaN,$15.00,1,$20.00,1,90,1,1,90,90,1.0,90.0,6 weeks ago,t,23,53,83,302,2019/09/14,75,15,2011/12/10,2019/05/29,90.0,9.0,10.0,10.0,10.0,10.0,9.0,f,NaN,NaN,f,f,moderate,f,f,1,0,1,0,0.79000000000000003553
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24189,38610335,2019/09/14,none,NaN,NaN,285240939,2019/08/13,within a few hours,100%,0.0,f,Yarraville/Seddon,6.0,6.0,"['email', 'phone', 'jumio', 'offline_governmen...",t,f,"Yarraville, VIC, Australia",Yarraville/Seddon,Maribyrnong,NaN,3013,-37.81226999999999804913,144.89830000000000609361,t,House,Shared room,1,1.5,1.0,1.0,1,"{TV,Wifi,Kitchen,""Free parking on premises"",He...",NaN,$35.00,NaN,NaN,NaN,NaN,1,$0.00,5,1125,5,5,1125,1125,5.0,1125.0,today,t,30,60,90,365,2019/09/14,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,f,f,flexible,f,f,6,0,0,6,NaN
24190,38610345,2019/09/14,none,NaN,Tram 59 and 57 are at the doorsteps. There are...,160772288,2017/11/30,within a few hours,96%,0.0,f,Footscray,19.0,19.0,"['email', 'phone']",t,f,"Flemington, VIC, Australia",Flemington,Moonee Valley,NaN,3031,-37.78645000000000209184,144.93334999999999013198,t,House,Shared room,4,2.0,1.0,1.0,1,"{TV,Wifi,Kitchen,""Free parking on premises"",""S...",NaN,$25.00,NaN,NaN,$200.00,$25.00,1,$24.00,14,1125,14,14,1125,1125,14.0,1125.0,today,t,30,60,90,365,2019/09/14,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,f,f,flexible,f,f,19,0,8,11,NaN
24191,38610653,2019/09/14,none,NaN,NaN,285240939,2019/08/13,within a few hours,100%,0.0,f,Yarraville/Seddon,6.0,6.0,"['email', 'phone', 'jumio', 'offline_governmen...",t,f,"Yarraville, VIC, Australia",Yarraville/Seddon,Maribyrnong,NaN,3013,-37.81226999999999804913,144.89830000000000609361,t,House,Shared room,1,1.5,1.0,1.0,1,"{TV,Wifi,Kitchen,""Free parking on premises"",He...",NaN,$35.00,NaN,NaN,NaN,NaN,1,$0.00,5,1125,5,5,1125,1125,5.0,1125.0,today,t,26,56,86,361,2019/09/14,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,f,f,flexible,f,f,6,0,0,6,NaN
24192,38612012,2019/09/15,none,NaN,NaN,50268144,2015/12/01,0,0,0.0,f,NaN,1.0,1.0,"['email', 'phone', 'facebook', 'reviews', 'wor...",t,f,"Richmond, VIC, Australia",Richmond,Yarra,NaN,3121,-37.81287000000000375621,145.00256000000001677108,f,Townhouse,Private room,1,1.0,1.0,1.0,1,"{TV,Wifi,Kitchen,""Free parking on premises"",""F...",NaN,$65.00,NaN,NaN,$200.00,$70.00,1,$0.00,2,1125,2,2,1125,1125,2.0,1125.0,today,t,28,58,88,116,2019/09/15,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,f,f,flexible,f,f,1,0,1,0,NaN
24193,38613509,2019/09/14,none,NaN,Marvel Stadium - adjacent Tram stop - outside...,50405671,2015/12/02,within an hour,95%,0.0,f,Southbank,16.0,16.0,"['email', 'phone', 'reviews', 'jumio', 'selfie...",t,f,"Docklands, VIC, Australia",Central Business District,Melbourne,NaN,3008,-37.81575000000000130740,144.94756000000000994987,t,Apartment,Entire home/apt,6,2.0,2.0,2.0,1,"{TV,""Cable TV"",Wifi,""Air conditioning"",Pool,Ki...",NaN,$140.00,NaN,NaN,$300.00,$120.00,4,$30.00,1,1125,1,1,1125,1125,1.0,1125.0,today,t,28,58,88,363,2019/09/14,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,NaN,f,f,strict_14_with_grace_period,f,f,17,17,0,0,NaN